version: '3'

services:
    mariadb:
        build: ./requirements/mariadb
        volumes:
            - inception-vol:/var/lib/mysql
        networks:
            - inception-net
        env_file:
            - .env
    wordpress:
        build: ./requirements/wordpress
        volumes:
            - inception-vol:/var/www/html
        networks:
            - inception-net
        depends_on:
            - mariadb
        env_file:
            - .env
    nginx:
        build: ./requirements/nginx
        volumes:
            - inception-vol:/usr/share/nginx/html
        networks:
            - inception-net
        depends_on:
            - wordpress
        ports:
            - "443:443"
            

networks:
    inception-net:
        name: inception
        driver: bridge

volumes:
    inception-vol: