version: '3'

services:
    mariadb:
        image: 'mariadb:42'
        container_name: mariadb
        build: ./requirements/mariadb
        volumes:
            - inception-vol:/var/lib/mysql
        networks:
            - inception-net
        env_file:
            - .env
    wordpress:
        image: 'wordpress:42'
        container_name: wordpress
        build: ./requirements/wordpress
        volumes:
            - wordpress-data:/var/www/inception
        networks:
            - inception-net
        depends_on:
            - mariadb
        env_file:
            - .env
    nginx:
        image: 'nginx:42'
        container_name: nginx
        build: ./requirements/nginx
        volumes:
            - wordpress-data:/var/www/inception
        networks:
            - inception-net
        depends_on:
            - wordpress
        ports:
            - "443:443"
            

networks:
    inception-net:
        name: inception
        driver: bridge

volumes:
    inception-vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: "$HOME/Desktop/data/mariadb"
    wordpress-data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: "$HOME/Desktop/data/wordpress-nginx"